services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
      target: development
    restart: unless-stopped
    volumes:
      - ./server/:/app/server/
      - ./data/vodding-data/:/data/
      - .env:/app/server/.env
    environment:
      NODE_ENV: development
      DATASTORE_FOLDER: /data/
      MONGO_URI: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/${MONGO_INITDB_DATABASE}?authSource=admin
    expose:
      - "5432"
    entrypoint: ["sh", "-c", "while :; do sleep 10; done"]

  # web:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.web
  #     target: development
  #   restart: unless-stopped
  #   volumes:
  #     - ./web:/app/web/
  #   expose:
  #     - "5173"
  #   entrypoint: ["sh", "-c", "while :; do sleep 10; done"]
  #   depends_on:
  #     - app

  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./caddy/Caddyfile.development:/etc/caddy/Caddyfile:ro

  mongo:
    extends:
      file: docker-compose.base.yaml
      service: mongo

  mongo-express:
    extends:
      file: docker-compose.base.yaml
      service: mongo-express

  redis:
    extends:
      file: docker-compose.base.yaml
      service: redis
