services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: app_development
    restart: unless-stopped
    volumes:
      - ./packages/app/:/app/packages/app/
      - ./data/vodding-data/:/data/
      - .env:/app/packages/app/.env
    environment:
      NODE_ENV: development
      DATASTORE_FOLDER: /data/
      MONGO_URI: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/${MONGO_INITDB_DATABASE}?authSource=admin
    expose:
      - "5432"
    entrypoint: ["sh", "-c", "while :; do sleep 10; done"]

  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: web_development
    restart: unless-stopped
    volumes:
      - ./packages/web:/app/packages/web/
    expose:
      - "5173"
    entrypoint: ["sh", "-c", "while :; do sleep 10; done"]
    depends_on:
      - app

  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/development.nginx.conf:/etc/nginx/nginx.conf:ro

  mongo:
    extends:
      file: docker-compose.base.yaml
      service: mongo

  mongo-express:
    extends:
      file: docker-compose.base.yaml
      service: mongo-express

  redis:
    extends:
      file: docker-compose.base.yaml
      service: redis
