services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: app_production
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data/vodding-data/:/data/
    environment:
      NODE_ENV: production
      DATASTORE_FOLDER: /data/
      MONGO_URI: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/${MONGO_INITDB_DATABASE}?authSource=admin
    depends_on:
      - mongo
      - redis:
          condition: service_healthy

  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: web_production
    restart: unless-stopped
    volumes:
      - ./nginx/production.nginx.conf:/etc/nginx/nginx.conf:ro
    environment:
      NODE_ENV: production
    ports:
      - "89:80"

  mongo:
    extends:
      file: docker-compose.base.yaml
      service: mongo

  mongo-express:
    extends:
      file: docker-compose.base.yaml
      service: mongo-express

  redis:
    extends:
      file: docker-compose.base.yaml
      service: redis
